// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiFinalMigoneGaston.Context;

namespace WebApiFinalMigoneGaston.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221118190741_NuevaBD")]
    partial class NuevaBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiFinalMigoneGaston.Entidades.Hospital", b =>
                {
                    b.Property<int>("HospitalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("NumCama")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("HospitalID");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("WebApiFinalMigoneGaston.Entidades.Medico", b =>
                {
                    b.Property<int>("MedicoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Especialidad")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("HospitalID")
                        .HasColumnType("int");

                    b.HasKey("MedicoID");

                    b.HasIndex("HospitalID");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("WebApiFinalMigoneGaston.Entidades.Medico", b =>
                {
                    b.HasOne("WebApiFinalMigoneGaston.Entidades.Hospital", "Hospital")
                        .WithMany("Medicos")
                        .HasForeignKey("HospitalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
